version: '3.8'

services:
  # 1. The Database Service
  postgres-db:
    image: postgres:15-alpine
    container_name: mindmirror-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mindmirrordb
    ports:
      - "5432:5432" # map to local machine
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persists DB data always
    healthcheck:
      # Ensures Postgres is fully booted before starting the Spring App
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. The Spring Boot Service
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mindmirror-app
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/mindmirrordb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - JWT_SECRET=dpqgUlBNoisndcUjkLsab0LDSrZuL54UGX9cRTQxkys
      - JWT_EXPIRATION=86400000
      - TRUGEN_API_KEY=${TRUGEN_API_KEY}
      - TRUGEN_AGENT_ID=${TRUGEN_AGENT_ID}

volumes:
  # Declares the named volume used by Postgres
  postgres-data: